name: staging-infra

on:
  push:
    branches:
      - develop
    paths:
      - "**/template.yml"
      - "**/template.yaml"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: SAM Build
        run: sam build

      - name: SAM Deploy
        run: sam deploy --stack-name staging-${{ vars.STACK_NAME }} --parameter-overrides StackName='staging-${{ vars.STACK_NAME }}' DomainName='${{vars.UI_DOMAIN}}'
